name: Scan CLI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-cli:
    runs-on: ubuntu-latest

    steps:
    # 1. Verificar el código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Docker
    - name: Build Docker Image
      run: |
        docker build -t scan-cli-image .

    # 3. Ejecutar análisis
    - name: Run Scan CLI
      run: |
        docker run --rm scan-cli-image ./scan-cli-plugin analyze --source ./src --report ./report.json

    # 4. Guardar el reporte como artefacto
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: scan-cli-report
        path: ./report.json