name: Scan CLI CI/CD
on:
push:
branches:
- main
pull_request:
branches:
- main
jobs:
scan-cli:
runs-on: ubuntu-latest
steps:
# 1. Verificar el c칩digo
- name: Checkout code
uses: actions/checkout@v3
# 2. Configurar Docker
- name: Build Docker Image
run: |
docker build -t scan-cli-image .
# 3. Ejecutar an치lisis
- name: Run Scan CLI
run: |
docker scout cves scan-cli-plugin:latest --report ./reports/report.json
# 4. Guardar el reporte como artefacto
- name: Upload Report
uses: actions/upload-artifact@v3
with:
name: scan-cli-report
path: ./report.json
- name: Notify Slack
  uses: slackapi/slack-github-action@v1.23.0
  with:
    channel-id: ${{ secrets.SLACK_CHANNEL }}
    slack-token: ${{ secrets.SLACK_TOKEN }}
    text: "El an치lisis de c칩digo se ha completado correctamente."